apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: browser-orchestrator
  namespace: browser-sessions
subjects:
  - kind: ServiceAccount
    name: browser-orchestrator
    namespace: browser-sessions
roleRef:
  kind: Role
  name: browser-orchestrator
  apiGroup: rbac.authorization.k8s.io
