// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  DeleteSessionsBySessionIdBy__Data,
  DeleteSessionsBySessionIdBy__Responses,
  DeleteSessionsBySessionIdData,
  DeleteSessionsBySessionIdResponses,
  GetData,
  GetHealthData,
  GetHealthResponses,
  GetResponses,
  GetSessionsBySessionIdBy__Data,
  GetSessionsBySessionIdBy__Responses,
  SessionRequest,
  SessionResponse,
  GetSessionsBySessionIdStatusData,
  GetSessionsBySessionIdStatusResponses,
  GetSessionsData,
  SessionsResponse,
  HeadSessionsBySessionIdBy__Data,
  HeadSessionsBySessionIdBy__Responses,
  OptionsSessionsBySessionIdBy__Data,
  OptionsSessionsBySessionIdBy__Responses,
  PatchSessionsBySessionIdBy__Data,
  PatchSessionsBySessionIdBy__Responses,
  PostSessionsBySessionIdBy__Data,
  PostSessionsBySessionIdBy__Responses,
  CreateSessionRequest,
  // CreateSessionResponses,
  PutSessionsBySessionIdBy__Data,
  PutSessionsBySessionIdBy__Responses,
  TraceSessionsBySessionIdBy__Data,
  TraceSessionsBySessionIdBy__Responses,
  SessionReleaseRequest,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const getSessions = <ThrowOnError extends boolean = false>(
  options?: Options<GetSessionsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SessionsResponse,
    unknown,
    ThrowOnError
  >({
    url: "/v1/sessions",
    ...options,
  });
};

export const createSession = <ThrowOnError extends boolean = false>(
  options?: Options<CreateSessionRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateSessionRequest,
    unknown,
    ThrowOnError
  >({
    url: "/v1/sessions",
    ...options,
  });
};

export const releaseSession = <ThrowOnError extends boolean = false>(
  options?: Options<SessionReleaseRequest, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SessionReleaseRequest,
    unknown,
    ThrowOnError
  >({
    url: "/v1/sessions/{sessionId}/release",
    ...options,
  });
};

export const deleteSessionsBySessionId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSessionsBySessionIdData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteSessionsBySessionIdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/sessions/{sessionId}",
    ...options,
  });
};

export const getSession = <ThrowOnError extends boolean = false>(
  options: Options<SessionRequest, ThrowOnError>,
) => {
  return (options.client ?? client).get<SessionResponse, unknown, ThrowOnError>(
    {
      url: "/sessions/{sessionId}",
      ...options,
    },
  );
};

export const getSessionsBySessionIdStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSessionsBySessionIdStatusData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetSessionsBySessionIdStatusResponses,
    unknown,
    ThrowOnError
  >({
    url: "/sessions/{sessionId}/status",
    ...options,
  });
};

export const getHealth = <ThrowOnError extends boolean = false>(
  options?: Options<GetHealthData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetHealthResponses,
    unknown,
    ThrowOnError
  >({
    url: "/health",
    ...options,
  });
};

export const get = <ThrowOnError extends boolean = false>(
  options?: Options<GetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetResponses, unknown, ThrowOnError>({
    url: "/",
    ...options,
  });
};

export const deleteSessionsBySessionIdBy__ = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteSessionsBySessionIdBy__Data, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteSessionsBySessionIdBy__Responses,
    unknown,
    ThrowOnError
  >({
    url: "/sessions/{sessionId}/{*}",
    ...options,
  });
};

export const getSessionsBySessionIdBy__ = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSessionsBySessionIdBy__Data, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetSessionsBySessionIdBy__Responses,
    unknown,
    ThrowOnError
  >({
    url: "/sessions/{sessionId}/{*}",
    ...options,
  });
};

export const headSessionsBySessionIdBy__ = <
  ThrowOnError extends boolean = false,
>(
  options: Options<HeadSessionsBySessionIdBy__Data, ThrowOnError>,
) => {
  return (options.client ?? client).head<
    HeadSessionsBySessionIdBy__Responses,
    unknown,
    ThrowOnError
  >({
    url: "/sessions/{sessionId}/{*}",
    ...options,
  });
};

export const optionsSessionsBySessionIdBy__ = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OptionsSessionsBySessionIdBy__Data, ThrowOnError>,
) => {
  return (options.client ?? client).options<
    OptionsSessionsBySessionIdBy__Responses,
    unknown,
    ThrowOnError
  >({
    url: "/sessions/{sessionId}/{*}",
    ...options,
  });
};

export const patchSessionsBySessionIdBy__ = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchSessionsBySessionIdBy__Data, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    PatchSessionsBySessionIdBy__Responses,
    unknown,
    ThrowOnError
  >({
    url: "/sessions/{sessionId}/{*}",
    ...options,
  });
};

export const postSessionsBySessionIdBy__ = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostSessionsBySessionIdBy__Data, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostSessionsBySessionIdBy__Responses,
    unknown,
    ThrowOnError
  >({
    url: "/sessions/{sessionId}/{*}",
    ...options,
  });
};

export const putSessionsBySessionIdBy__ = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutSessionsBySessionIdBy__Data, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    PutSessionsBySessionIdBy__Responses,
    unknown,
    ThrowOnError
  >({
    url: "/sessions/{sessionId}/{*}",
    ...options,
  });
};

export const traceSessionsBySessionIdBy__ = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TraceSessionsBySessionIdBy__Data, ThrowOnError>,
) => {
  return (options.client ?? client).trace<
    TraceSessionsBySessionIdBy__Responses,
    unknown,
    ThrowOnError
  >({
    url: "/sessions/{sessionId}/{*}",
    ...options,
  });
};
