// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:80/api" | (string & {});
};

/**
 * An error response from the API
 */
export type ErrorResponse = {
  message: string;
  error?: string;
  context?: Array<{
    keyword: string;
    params?: unknown;
    message: string;
  }>;
  status: number;
};

export type GetSessionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/sessions";
};

export type SessionsResponse = {
  /**
   * List of browser sessions
   */
  sessions: Array<{
    /**
     * Unique identifier for the session
     */
    id: string;
    /**
     * Timestamp when the session started
     */
    createdAt: Date;
    /**
     * Status of the session
     */
    status: "live" | "released" | "failed";
    /**
     * Duration of the session in milliseconds
     */
    duration: number;
    /**
     * Number of events processed in the session
     */
    eventCount: number;
    /**
     * Session timeout duration in milliseconds
     */
    timeout: number;
    /**
     * Viewport and browser window dimensions for the session
     */
    dimensions: {
      /**
       * Width of the browser window
       */
      width: number;
      /**
       * Height of the browser window
       */
      height: number;
    };
    /**
     * Amount of credits consumed by the session
     */
    creditsUsed: number;
    /**
     * URL for the session's WebSocket connection
     */
    websocketUrl: string;
    /**
     * URL for debugging the session
     */
    debugUrl: string;
    /**
     * URL to view session details
     */
    sessionViewerUrl: string;
    /**
     * User agent string used in the session
     */
    userAgent?: string;
    /**
     * Source of the proxy used for the session
     */
    proxySource: ("steel" | "external") | null;
    /**
     * Amount of data transmitted through the proxy
     */
    proxyBytesUsed: number;
    /**
     * Indicates if captcha solving is enabled
     */
    solveCaptcha?: boolean;
    /**
     * Indicates if Selenium is used in the session
     */
    isSelenium?: boolean;
    /**
     * Stealth configuration for the session
     */
    stealthConfig?: {
      /**
       * This flag will make the browser act more human-like by moving the mouse in a more natural way
       */
      humanizeInteractions?: boolean;
      /**
       * This flag will skip the fingerprint generation for the session.
       */
      skipFingerprintInjection?: boolean;
    };
    /**
     * The region where the session was created
     */
    region?: "lax" | "ord" | "iad" | "scl" | "fra" | "nrt";
    /**
     * The ID of the profile associated with the session
     */
    profileId?: string;
    /**
     * This flag will persist the profile for the session.
     */
    persistProfile?: boolean;
    /**
     * Bandwidth optimizations that were applied to the session.
     */
    optimizeBandwidth: {
      blockImages?: boolean;
      blockMedia?: boolean;
      blockStylesheets?: boolean;
      blockHosts?: Array<string>;
      blockUrlPatterns?: Array<string>;
    };
    /**
     * Device configuration for the session
     */
    deviceConfig?: {
      device?: "desktop" | "mobile";
    };
    /**
     * Indicates if the session is headless or headful
     */
    headless?: boolean;
  }>;
};

export type CreateSessionRequest = {
  body?: CreateSessionRequest;
  path?: never;
  query?: never;
  url: "/sessions";
};

export type CreateSessionResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type DeleteSessionsBySessionIdData = {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: "/sessions/{sessionId}";
};

export type DeleteSessionsBySessionIdResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type SessionRequest = {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: "/sessions/{sessionId}";
};

export type SessionReleaseRequest = {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: "/sessions/{sessionId}/release";
};

export type ReleaseSessionResponse = {
  success: boolean;
  sessionId: string;
  status: string;
  error?: string;
};

export type SessionResponse = {
  /**
   * Unique identifier for the session
   */
  id: string;
  /**
   * Timestamp when the session started
   */
  createdAt: Date;
  /**
   * Status of the session
   */
  status: "live" | "released" | "failed";
  /**
   * Duration of the session in milliseconds
   */
  duration: number;
  /**
   * Number of events processed in the session
   */
  eventCount: number;
  /**
   * Session timeout duration in milliseconds
   */
  timeout: number;
  /**
   * Viewport and browser window dimensions for the session
   */
  dimensions: {
    /**
     * Width of the browser window
     */
    width: number;
    /**
     * Height of the browser window
     */
    height: number;
  };
  /**
   * Amount of credits consumed by the session
   */
  creditsUsed: number;
  /**
   * URL for the session's WebSocket connection
   */
  websocketUrl: string;
  /**
   * URL for debugging the session
   */
  debugUrl: string;
  /**
   * URL to view session details
   */
  sessionViewerUrl: string;
  /**
   * User agent string used in the session
   */
  userAgent?: string;
  /**
   * Source of the proxy used for the session
   */
  proxySource: ("steel" | "external") | null;
  /**
   * Amount of data transmitted through the proxy
   */
  proxyBytesUsed: number;
  /**
   * Indicates if captcha solving is enabled
   */
  solveCaptcha?: boolean;
  /**
   * Indicates if Selenium is used in the session
   */
  isSelenium?: boolean;
  /**
   * Stealth configuration for the session
   */
  stealthConfig?: {
    /**
     * This flag will make the browser act more human-like by moving the mouse in a more natural way
     */
    humanizeInteractions?: boolean;
    /**
     * This flag will skip the fingerprint generation for the session.
     */
    skipFingerprintInjection?: boolean;
  };
  /**
   * The region where the session was created
   */
  region?: "lax" | "ord" | "iad" | "scl" | "fra" | "nrt";
  /**
   * The ID of the profile associated with the session
   */
  profileId?: string;
  /**
   * This flag will persist the profile for the session.
   */
  persistProfile?: boolean;
  /**
   * Bandwidth optimizations that were applied to the session.
   */
  optimizeBandwidth: {
    blockImages?: boolean;
    blockMedia?: boolean;
    blockStylesheets?: boolean;
    blockHosts?: Array<string>;
    blockUrlPatterns?: Array<string>;
  };
  /**
   * Device configuration for the session
   */
  deviceConfig?: {
    device?: "desktop" | "mobile";
  };
  /**
   * Indicates if the session is headless or headful
   */
  headless?: boolean;
};

export type GetSessionsBySessionIdStatusData = {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: "/sessions/{sessionId}/status";
};

export type GetSessionsBySessionIdStatusResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type GetHealthResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type GetResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type DeleteSessionsBySessionIdBy__Data = {
  body?: never;
  path: {
    sessionId: string;
    "*": string;
  };
  query?: never;
  url: "/sessions/{sessionId}/{*}";
};

export type DeleteSessionsBySessionIdBy__Responses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetSessionsBySessionIdBy__Data = {
  body?: never;
  path: {
    sessionId: string;
    "*": string;
  };
  query?: never;
  url: "/sessions/{sessionId}/{*}";
};

export type GetSessionsBySessionIdBy__Responses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type HeadSessionsBySessionIdBy__Data = {
  body?: never;
  path: {
    sessionId: string;
    "*": string;
  };
  query?: never;
  url: "/sessions/{sessionId}/{*}";
};

export type HeadSessionsBySessionIdBy__Responses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type OptionsSessionsBySessionIdBy__Data = {
  body?: never;
  path: {
    sessionId: string;
    "*": string;
  };
  query?: never;
  url: "/sessions/{sessionId}/{*}";
};

export type OptionsSessionsBySessionIdBy__Responses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PatchSessionsBySessionIdBy__Data = {
  body?: never;
  path: {
    sessionId: string;
    "*": string;
  };
  query?: never;
  url: "/sessions/{sessionId}/{*}";
};

export type PatchSessionsBySessionIdBy__Responses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostSessionsBySessionIdBy__Data = {
  body?: never;
  path: {
    sessionId: string;
    "*": string;
  };
  query?: never;
  url: "/sessions/{sessionId}/{*}";
};

export type PostSessionsBySessionIdBy__Responses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PutSessionsBySessionIdBy__Data = {
  body?: never;
  path: {
    sessionId: string;
    "*": string;
  };
  query?: never;
  url: "/sessions/{sessionId}/{*}";
};

export type PutSessionsBySessionIdBy__Responses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type TraceSessionsBySessionIdBy__Data = {
  body?: never;
  path: {
    sessionId: string;
    "*": string;
  };
  query?: never;
  url: "/sessions/{sessionId}/{*}";
};

export type TraceSessionsBySessionIdBy__Responses = {
  /**
   * Default Response
   */
  200: unknown;
};
