services:
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  orchestrator:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - K8S_NAMESPACE=default
      - BROWSER_IMAGE=your-browser:latest
      - MAX_SESSIONS=50
    depends_on:
      - redis
    volumes:
      - ~/.kube:/home/orchestrator/.kube:ro

volumes:
  redis_data:
