{{- if .Values.ingress.enabled }}
{{- $ns := include "steel-cluster.namespace" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "steel-cluster.fullname" . }}
  namespace: {{ $ns }}
  labels:
{{ include "steel-cluster.labels" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
  rules:
{{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
{{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .service.name }}
                port:
{{- if kindIs "string" .service.port }}
                  name: {{ .service.port }}
{{- else }}
                  number: {{ .service.port }}
{{- end }}
{{- end }}
{{- end }}
{{- with .Values.ingress.tls }}
  tls:
{{ toYaml . | nindent 4 }}
{{- end }}
{{- end }}
