{{- /*
Template: Orchestrator RBAC (ServiceAccount, Role, RoleBinding)
*/ -}}
{{- $ns := include "steel-cluster.namespace" . -}}
{{- $saName := include "steel-cluster.orchestrator.serviceAccountName" . -}}

{{- if and .Values.orchestrator.enabled .Values.orchestrator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  namespace: {{ $ns }}
  labels:
{{ include "steel-cluster.labels" . | nindent 4 }}
{{- $saAnn := .Values.orchestrator.serviceAccount.annotations }}
{{- if $saAnn }}
  annotations:
{{ toYaml $saAnn | nindent 4 }}
{{- end }}
{{- end }}

{{- if and .Values.orchestrator.enabled .Values.orchestrator.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $saName }}
  namespace: {{ $ns }}
  labels:
{{ include "steel-cluster.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $saName }}
  namespace: {{ $ns }}
  labels:
{{ include "steel-cluster.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $saName }}
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ $ns }}
{{- end }}
