apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: browser-sessions
data:
  browser-sessions.yml: |
    groups:
    - name: browser-sessions
      rules:
      - alert: HighSessionCount
        expr: browser_sessions_total > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of active browser sessions"
          description: "Number of active sessions ({{ $value }}) is above 80"

      - alert: SessionCreationFailure
        expr: increase(browser_sessions_failed[5m]) > 5
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High session creation failure rate"
          description: "{{ $value }} sessions failed to start in the last 5 minutes"

      - alert: OrchestratorDown
        expr: up{job="browser-orchestrator"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Browser orchestrator is down"
          description: "The browser session orchestrator is not responding"

      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis instance is not responding"
