apiVersion: v1
kind: Service
metadata:
  name: browser-orchestrator
  namespace: browser-sessions
spec:
  selector:
    app: browser-orchestrator
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
